/*
 * -----------------------------------------------------------------------
 *
 * NOTE: Do *not* edit this file; instead, edit 'erl_alloc.types' and
 *       build again! This file was automatically generated by
 *       'make_alloc_types' on Mon Jan 19 19:22:59 2015.
 *
 * -----------------------------------------------------------------------
 *
 * ``The contents of this file are subject to the Erlang Public License,
 * Version 1.1, (the "License"); you may not use this file except in
 * compliance with the License. You should have received a copy of the
 * Erlang Public License along with this software. If not, it can be
 * retrieved via the world wide web at http://www.erlang.org/.
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
 * the License for the specific language governing rights and limitations
 * under the License.
 *
 * The Initial Developer of the Original Code is Ericsson Utvecklings AB.
 * Portions created by Ericsson are Copyright 1999, Ericsson Utvecklings
 * AB. All Rights Reserved.''
 */

#ifndef ERL_ALLOC_TYPES_H__
#define ERL_ALLOC_TYPES_H__


/* --- Allocator numbers -------------------------------------------------- */

#define ERTS_ALC_A_INVALID (0)

#define ERTS_ALC_A_MIN (1)

#define ERTS_ALC_A_SYSTEM (1)
#define ERTS_ALC_A_TEMPORARY (2)
#define ERTS_ALC_A_SHORT_LIVED (3)
#define ERTS_ALC_A_STANDARD (4)
#define ERTS_ALC_A_LONG_LIVED (5)
#define ERTS_ALC_A_EHEAP (6)
#define ERTS_ALC_A_ETS (7)
#define ERTS_ALC_A_FIXED_SIZE (8)
#define ERTS_ALC_A_BINARY (9)
#define ERTS_ALC_A_DRIVER (10)

#define ERTS_ALC_A_MAX (10)


/* --- Class numbers ------------------------------------------------------ */

#define ERTS_ALC_C_INVALID (0)

#define ERTS_ALC_C_MIN (1)

#define ERTS_ALC_C_PROCESSES  (1)
#define ERTS_ALC_C_CODE  (2)
#define ERTS_ALC_C_SYSTEM  (3)
#define ERTS_ALC_C_ATOM  (4)
#define ERTS_ALC_C_ETS  (5)
#define ERTS_ALC_C_BINARIES  (6)

#define ERTS_ALC_C_MAX (6)


/* --- Type number intervals ---------------------------------------------- */

#define ERTS_ALC_N_INVALID (0)

#define ERTS_ALC_N_MIN (1)

/* Type numbers used for sys_alloc */
#define ERTS_ALC_N_MIN_A_SYSTEM (1)
#define ERTS_ALC_N_MAX_A_SYSTEM (5)

/* Type numbers used for temp_alloc */
#define ERTS_ALC_N_MIN_A_TEMPORARY (6)
#define ERTS_ALC_N_MAX_A_TEMPORARY (24)

/* Type numbers used for sl_alloc */
#define ERTS_ALC_N_MIN_A_SHORT_LIVED (25)
#define ERTS_ALC_N_MAX_A_SHORT_LIVED (44)

/* Type numbers used for std_alloc */
#define ERTS_ALC_N_MIN_A_STANDARD (45)
#define ERTS_ALC_N_MAX_A_STANDARD (74)

/* Type numbers used for ll_alloc */
#define ERTS_ALC_N_MIN_A_LONG_LIVED (75)
#define ERTS_ALC_N_MAX_A_LONG_LIVED (98)

/* Type numbers used for eheap_alloc */
#define ERTS_ALC_N_MIN_A_EHEAP (99)
#define ERTS_ALC_N_MAX_A_EHEAP (101)

/* Type numbers used for ets_alloc */
#define ERTS_ALC_N_MIN_A_ETS (102)
#define ERTS_ALC_N_MAX_A_ETS (109)

/* Type numbers used for fix_alloc */
#define ERTS_ALC_N_MIN_A_FIXED_SIZE (110)
#define ERTS_ALC_N_MAX_A_FIXED_SIZE (121)

/* Type numbers used for binary_alloc */
#define ERTS_ALC_N_MIN_A_BINARY (122)
#define ERTS_ALC_N_MAX_A_BINARY (123)

/* Type numbers used for driver_alloc */
#define ERTS_ALC_N_MIN_A_DRIVER (124)
#define ERTS_ALC_N_MAX_A_DRIVER (130)

#define ERTS_ALC_N_MAX (130)


/* --- Multi thread use of allocators -------------------------------------- */

#define ERTS_ALC_MTA_SYSTEM (1)
#define ERTS_ALC_MTA_TEMPORARY (0)
#define ERTS_ALC_MTA_SHORT_LIVED (0)
#define ERTS_ALC_MTA_STANDARD (0)
#define ERTS_ALC_MTA_LONG_LIVED (0)
#define ERTS_ALC_MTA_EHEAP (0)
#define ERTS_ALC_MTA_ETS (0)
#define ERTS_ALC_MTA_FIXED_SIZE (0)
#define ERTS_ALC_MTA_BINARY (1)
#define ERTS_ALC_MTA_DRIVER (1)


/* --- Types --------------------------------------------------------------- */

typedef Uint32 ErtsAlcType_t; /* The type used for memory types */

#define ERTS_ALC_T_INVALID (0)

#define ERTS_ALC_T_UNDEF (177)
#define ERTS_ALC_T_NBIF_TABLE (305)
#define ERTS_ALC_T_INFO_DSBUF (433)
#define ERTS_ALC_T_ETHR_INTERNAL (561)
#define ERTS_ALC_T_PUTENV_STR (689)
#define ERTS_ALC_T_TMP_HEAP (786)
#define ERTS_ALC_T_MSG_ROOTS (914)
#define ERTS_ALC_T_ROOTSET (1042)
#define ERTS_ALC_T_LOADER_TMP (1186)
#define ERTS_ALC_T_NC_TMP (1330)
#define ERTS_ALC_T_TMP (1458)
#define ERTS_ALC_T_DCTRL_BUF (1586)
#define ERTS_ALC_T_TMP_DIST_BUF (1714)
#define ERTS_ALC_T_ESTACK (1842)
#define ERTS_ALC_T_PORT_CALL_BUF (1970)
#define ERTS_ALC_T_DB_TMP (2130)
#define ERTS_ALC_T_DB_MC_STK (2258)
#define ERTS_ALC_T_DB_MS_CMPL_HEAP (2386)
#define ERTS_ALC_T_LOGGER_DSBUF (2482)
#define ERTS_ALC_T_TMP_DSBUF (2610)
#define ERTS_ALC_T_DDLL_TMP_BUF (2738)
#define ERTS_ALC_T_RE_TMP_BUF (2866)
#define ERTS_ALC_T_SYS_READ_BUF (2994)
#define ERTS_ALC_T_ENVIRONMENT (3122)
#define ERTS_ALC_T_PEND_SUSPEND (3219)
#define ERTS_ALC_T_MSG_REF (3347)
#define ERTS_ALC_T_SL_BIF_TIMER (3475)
#define ERTS_ALC_T_ASYNC (3635)
#define ERTS_ALC_T_DB_FIXATION (3795)
#define ERTS_ALC_T_DB_FIX_DEL (3923)
#define ERTS_ALC_T_DB_MS_RUN_HEAP (4051)
#define ERTS_ALC_T_DB_PROC_CLEANUP (4179)
#define ERTS_ALC_T_PORT_TASK (4275)
#define ERTS_ALC_T_PORT_TASKQ (4403)
#define ERTS_ALC_T_MISC_OP_LIST (4531)
#define ERTS_ALC_T_PORT_NAMES (4659)
#define ERTS_ALC_T_PROCS_TPROC_EL (4755)
#define ERTS_ALC_T_PROCS_CNKINF (4883)
#define ERTS_ALC_T_PROCS_PIDS (5011)
#define ERTS_ALC_T_RE_SUBJECT (5171)
#define ERTS_ALC_T_RE_STACK (5299)
#define ERTS_ALC_T_UNICODE_BUFFER (5427)
#define ERTS_ALC_T_FD_LIST (5555)
#define ERTS_ALC_T_POLLSET_UPDREQ (5683)
#define ERTS_ALC_T_LINK_LH (5780)
#define ERTS_ALC_T_MONITOR_LH (5908)
#define ERTS_ALC_T_NLINK_LH (6036)
#define ERTS_ALC_T_SUSPEND_MON (6164)
#define ERTS_ALC_T_LL_BIF_TIMER (6292)
#define ERTS_ALC_T_REG_TABLE (6452)
#define ERTS_ALC_T_FUN_TABLE (6564)
#define ERTS_ALC_T_DIST_TABLE (6708)
#define ERTS_ALC_T_NODE_TABLE (6836)
#define ERTS_ALC_T_MODULE_REFS (6948)
#define ERTS_ALC_T_DCACHE (7092)
#define ERTS_ALC_T_DIST_ENTRY (7220)
#define ERTS_ALC_T_NODE_ENTRY (7348)
#define ERTS_ALC_T_DRIVER (7476)
#define ERTS_ALC_T_ARG_REG (7572)
#define ERTS_ALC_T_PROC_DICT (7700)
#define ERTS_ALC_T_CALLS_BUF (7828)
#define ERTS_ALC_T_BPD (7988)
#define ERTS_ALC_T_PORT_NAME (8116)
#define ERTS_ALC_T_LINEBUF (8244)
#define ERTS_ALC_T_IOQ (8372)
#define ERTS_ALC_T_BITS_BUF (8500)
#define ERTS_ALC_T_DB_NTAB_ENT (8660)
#define ERTS_ALC_T_DDLL_PROCESS (8756)
#define ERTS_ALC_T_DDLL_HANDLE (8884)
#define ERTS_ALC_T_PORT_DATA_LOCK (9012)
#define ERTS_ALC_T_NODES_MON (9108)
#define ERTS_ALC_T_RE_HEAP (9268)
#define ERTS_ALC_T_FD_ENTRY_BUF (9396)
#define ERTS_ALC_T_PRT_REP_EXIT (9524)
#define ERTS_ALC_T_ATOM_TXT (9669)
#define ERTS_ALC_T_BIF_TIMER_TABLE (9781)
#define ERTS_ALC_T_ATOM_TABLE (9925)
#define ERTS_ALC_T_EXPORT_TABLE (10021)
#define ERTS_ALC_T_MODULE_TABLE (10149)
#define ERTS_ALC_T_PROC_TABLE (10261)
#define ERTS_ALC_T_PORT_TABLE (10421)
#define ERTS_ALC_T_TIMER_WHEEL (10549)
#define ERTS_ALC_T_CODE (10661)
#define ERTS_ALC_T_ASYNC_Q (10805)
#define ERTS_ALC_T_DB_TABLES (10965)
#define ERTS_ALC_T_DB_MS_PSDO_PROC (11093)
#define ERTS_ALC_T_INSTR_INFO (11189)
#define ERTS_ALC_T_SCHDLR_DATA (11285)
#define ERTS_ALC_T_DDLL_ERRCODES (11445)
#define ERTS_ALC_T_PRE_ALLOC_DATA (11573)
#define ERTS_ALC_T_DRV_TAB (11701)
#define ERTS_ALC_T_DRV_EV_STATE (11829)
#define ERTS_ALC_T_POLLSET (11957)
#define ERTS_ALC_T_POLL_FDS (12085)
#define ERTS_ALC_T_POLL_RES_EVS (12213)
#define ERTS_ALC_T_FD_STATUS (12341)
#define ERTS_ALC_T_FD_TAB (12469)
#define ERTS_ALC_T_CS_PROG_PATH (12597)
#define ERTS_ALC_T_HEAP (12694)
#define ERTS_ALC_T_OLD_HEAP (12822)
#define ERTS_ALC_T_HEAP_FRAG (12950)
#define ERTS_ALC_T_DB_SEG (13143)
#define ERTS_ALC_T_DB_SEG_TAB (13271)
#define ERTS_ALC_T_DB_STK (13399)
#define ERTS_ALC_T_DB_TRANS_TAB (13527)
#define ERTS_ALC_T_DB_SEL_LIST (13655)
#define ERTS_ALC_T_DB_DMC_ERROR (13783)
#define ERTS_ALC_T_DB_DMC_ERR_INFO (13911)
#define ERTS_ALC_T_DB_TERM (14039)
#define ERTS_ALC_T_PROC (14104)
#define ERTS_ALC_T_ATOM (14280)
#define ERTS_ALC_T_EXPORT (14376)
#define ERTS_ALC_T_MODULE (14504)
#define ERTS_ALC_T_REG_PROC (14616)
#define ERTS_ALC_T_MONITOR_SH (14744)
#define ERTS_ALC_T_NLINK_SH (14872)
#define ERTS_ALC_T_PROC_LIST (15000)
#define ERTS_ALC_T_FUN_ENTRY (15144)
#define ERTS_ALC_T_DB_TABLE (15320)
#define ERTS_ALC_T_DRV_EV_D_STATE (15416)
#define ERTS_ALC_T_DRV_SEL_D_STATE (15544)
#define ERTS_ALC_T_DRV_BINARY (15721)
#define ERTS_ALC_T_BINARY (15849)
#define ERTS_ALC_T_DRV (15930)
#define ERTS_ALC_T_DRV_THR_OPTS (16058)
#define ERTS_ALC_T_DRV_TID (16186)
#define ERTS_ALC_T_DRV_MTX (16314)
#define ERTS_ALC_T_DRV_CND (16442)
#define ERTS_ALC_T_DRV_RWLCK (16570)
#define ERTS_ALC_T_DRV_TSD (16698)


/* --- Field sizes, masks, and shifts -------------------------------------- */

#define ERTS_ALC_A_BITS (4)
#define ERTS_ALC_C_BITS (3)
#define ERTS_ALC_N_BITS (8)
#define ERTS_ALC_T_BITS (15)

#define ERTS_ALC_A_MASK (15)
#define ERTS_ALC_C_MASK (7)
#define ERTS_ALC_N_MASK (255)
#define ERTS_ALC_T_MASK (32767)

#define ERTS_ALC_A_SHIFT (0)
#define ERTS_ALC_C_SHIFT (4)
#define ERTS_ALC_N_SHIFT (7)


/* --- Mappings ------------------------------------------------------------ */

/* type -> type number */
#define ERTS_ALC_T2N(T) (((T) >> ERTS_ALC_N_SHIFT) & ERTS_ALC_N_MASK)

/* type -> allocator number */
#define ERTS_ALC_T2A(T) (((T) >> ERTS_ALC_A_SHIFT) & ERTS_ALC_A_MASK)

/* type -> class number */
#define ERTS_ALC_T2C(T) (((T) >> ERTS_ALC_C_SHIFT) & ERTS_ALC_C_MASK)

/* type number -> type */
#define ERTS_ALC_N2T(N) (erts_alc_n2t[(N)])

/* type number -> type description */
#define ERTS_ALC_N2TD(N) (erts_alc_n2td[(N)])

/* type -> type description */
#define ERTS_ALC_T2TD(T) (ERTS_ALC_N2TD(ERTS_ALC_T2N((T))))

/* class number -> class description */
#define ERTS_ALC_C2CD(C) (erts_alc_c2cd[(C)])

/* allocator number -> allocator description */
#define ERTS_ALC_A2AD(A) (erts_alc_a2ad[(A)])

extern const ErtsAlcType_t erts_alc_n2t[];
extern const char *erts_alc_n2td[];
extern const char *erts_alc_c2cd[];
extern const char *erts_alc_a2ad[];

#ifdef ERTS_ALC_INTERNAL__

const ErtsAlcType_t erts_alc_n2t[] = {
  ERTS_ALC_T_INVALID,
  ERTS_ALC_T_UNDEF,
  ERTS_ALC_T_NBIF_TABLE,
  ERTS_ALC_T_INFO_DSBUF,
  ERTS_ALC_T_ETHR_INTERNAL,
  ERTS_ALC_T_PUTENV_STR,
  ERTS_ALC_T_TMP_HEAP,
  ERTS_ALC_T_MSG_ROOTS,
  ERTS_ALC_T_ROOTSET,
  ERTS_ALC_T_LOADER_TMP,
  ERTS_ALC_T_NC_TMP,
  ERTS_ALC_T_TMP,
  ERTS_ALC_T_DCTRL_BUF,
  ERTS_ALC_T_TMP_DIST_BUF,
  ERTS_ALC_T_ESTACK,
  ERTS_ALC_T_PORT_CALL_BUF,
  ERTS_ALC_T_DB_TMP,
  ERTS_ALC_T_DB_MC_STK,
  ERTS_ALC_T_DB_MS_CMPL_HEAP,
  ERTS_ALC_T_LOGGER_DSBUF,
  ERTS_ALC_T_TMP_DSBUF,
  ERTS_ALC_T_DDLL_TMP_BUF,
  ERTS_ALC_T_RE_TMP_BUF,
  ERTS_ALC_T_SYS_READ_BUF,
  ERTS_ALC_T_ENVIRONMENT,
  ERTS_ALC_T_PEND_SUSPEND,
  ERTS_ALC_T_MSG_REF,
  ERTS_ALC_T_SL_BIF_TIMER,
  ERTS_ALC_T_ASYNC,
  ERTS_ALC_T_DB_FIXATION,
  ERTS_ALC_T_DB_FIX_DEL,
  ERTS_ALC_T_DB_MS_RUN_HEAP,
  ERTS_ALC_T_DB_PROC_CLEANUP,
  ERTS_ALC_T_PORT_TASK,
  ERTS_ALC_T_PORT_TASKQ,
  ERTS_ALC_T_MISC_OP_LIST,
  ERTS_ALC_T_PORT_NAMES,
  ERTS_ALC_T_PROCS_TPROC_EL,
  ERTS_ALC_T_PROCS_CNKINF,
  ERTS_ALC_T_PROCS_PIDS,
  ERTS_ALC_T_RE_SUBJECT,
  ERTS_ALC_T_RE_STACK,
  ERTS_ALC_T_UNICODE_BUFFER,
  ERTS_ALC_T_FD_LIST,
  ERTS_ALC_T_POLLSET_UPDREQ,
  ERTS_ALC_T_LINK_LH,
  ERTS_ALC_T_MONITOR_LH,
  ERTS_ALC_T_NLINK_LH,
  ERTS_ALC_T_SUSPEND_MON,
  ERTS_ALC_T_LL_BIF_TIMER,
  ERTS_ALC_T_REG_TABLE,
  ERTS_ALC_T_FUN_TABLE,
  ERTS_ALC_T_DIST_TABLE,
  ERTS_ALC_T_NODE_TABLE,
  ERTS_ALC_T_MODULE_REFS,
  ERTS_ALC_T_DCACHE,
  ERTS_ALC_T_DIST_ENTRY,
  ERTS_ALC_T_NODE_ENTRY,
  ERTS_ALC_T_DRIVER,
  ERTS_ALC_T_ARG_REG,
  ERTS_ALC_T_PROC_DICT,
  ERTS_ALC_T_CALLS_BUF,
  ERTS_ALC_T_BPD,
  ERTS_ALC_T_PORT_NAME,
  ERTS_ALC_T_LINEBUF,
  ERTS_ALC_T_IOQ,
  ERTS_ALC_T_BITS_BUF,
  ERTS_ALC_T_DB_NTAB_ENT,
  ERTS_ALC_T_DDLL_PROCESS,
  ERTS_ALC_T_DDLL_HANDLE,
  ERTS_ALC_T_PORT_DATA_LOCK,
  ERTS_ALC_T_NODES_MON,
  ERTS_ALC_T_RE_HEAP,
  ERTS_ALC_T_FD_ENTRY_BUF,
  ERTS_ALC_T_PRT_REP_EXIT,
  ERTS_ALC_T_ATOM_TXT,
  ERTS_ALC_T_BIF_TIMER_TABLE,
  ERTS_ALC_T_ATOM_TABLE,
  ERTS_ALC_T_EXPORT_TABLE,
  ERTS_ALC_T_MODULE_TABLE,
  ERTS_ALC_T_PROC_TABLE,
  ERTS_ALC_T_PORT_TABLE,
  ERTS_ALC_T_TIMER_WHEEL,
  ERTS_ALC_T_CODE,
  ERTS_ALC_T_ASYNC_Q,
  ERTS_ALC_T_DB_TABLES,
  ERTS_ALC_T_DB_MS_PSDO_PROC,
  ERTS_ALC_T_INSTR_INFO,
  ERTS_ALC_T_SCHDLR_DATA,
  ERTS_ALC_T_DDLL_ERRCODES,
  ERTS_ALC_T_PRE_ALLOC_DATA,
  ERTS_ALC_T_DRV_TAB,
  ERTS_ALC_T_DRV_EV_STATE,
  ERTS_ALC_T_POLLSET,
  ERTS_ALC_T_POLL_FDS,
  ERTS_ALC_T_POLL_RES_EVS,
  ERTS_ALC_T_FD_STATUS,
  ERTS_ALC_T_FD_TAB,
  ERTS_ALC_T_CS_PROG_PATH,
  ERTS_ALC_T_HEAP,
  ERTS_ALC_T_OLD_HEAP,
  ERTS_ALC_T_HEAP_FRAG,
  ERTS_ALC_T_DB_SEG,
  ERTS_ALC_T_DB_SEG_TAB,
  ERTS_ALC_T_DB_STK,
  ERTS_ALC_T_DB_TRANS_TAB,
  ERTS_ALC_T_DB_SEL_LIST,
  ERTS_ALC_T_DB_DMC_ERROR,
  ERTS_ALC_T_DB_DMC_ERR_INFO,
  ERTS_ALC_T_DB_TERM,
  ERTS_ALC_T_PROC,
  ERTS_ALC_T_ATOM,
  ERTS_ALC_T_EXPORT,
  ERTS_ALC_T_MODULE,
  ERTS_ALC_T_REG_PROC,
  ERTS_ALC_T_MONITOR_SH,
  ERTS_ALC_T_NLINK_SH,
  ERTS_ALC_T_PROC_LIST,
  ERTS_ALC_T_FUN_ENTRY,
  ERTS_ALC_T_DB_TABLE,
  ERTS_ALC_T_DRV_EV_D_STATE,
  ERTS_ALC_T_DRV_SEL_D_STATE,
  ERTS_ALC_T_DRV_BINARY,
  ERTS_ALC_T_BINARY,
  ERTS_ALC_T_DRV,
  ERTS_ALC_T_DRV_THR_OPTS,
  ERTS_ALC_T_DRV_TID,
  ERTS_ALC_T_DRV_MTX,
  ERTS_ALC_T_DRV_CND,
  ERTS_ALC_T_DRV_RWLCK,
  ERTS_ALC_T_DRV_TSD,
  ERTS_ALC_T_INVALID
};

const char *erts_alc_n2td[] = {
  "invalid_type",
  "undefined",
  "nbif_tab",
  "info_dsbuf",
  "ethread_internal",
  "putenv_string",
  "tmp_heap",
  "msg_roots",
  "root_set",
  "loader_tmp",
  "nc_tmp",
  "tmp",
  "dctrl_buf",
  "tmp_dist_buf",
  "estack",
  "port_call_buf",
  "db_tmp",
  "db_mc_stack",
  "db_match_spec_cmpl_heap",
  "logger_dsbuf",
  "tmp_dsbuf",
  "ddll_tmp_buf",
  "re_tmp_buf",
  "sys_read_buf",
  "environment",
  "pending_suspend",
  "msg_ref",
  "bif_timer_sl",
  "async",
  "db_fixation",
  "fixed_del",
  "db_match_spec_run_heap",
  "db_proc_cleanup_state",
  "port_task",
  "port_task_queue",
  "misc_op_list",
  "port_names",
  "processes_term_proc_el",
  "processes_chunk_info",
  "processes_pids",
  "re_subject",
  "re_stack",
  "unicode_buffer",
  "fd_list",
  "pollset_update_req",
  "link_lh",
  "monitor_lh",
  "nlink_lh",
  "suspend_monitor",
  "bif_timer_ll",
  "reg_tab",
  "fun_tab",
  "dist_tab",
  "node_tab",
  "module_refs",
  "dcache",
  "dist_entry",
  "node_entry",
  "driver",
  "arg_reg",
  "proc_dict",
  "calls_buf",
  "bpd",
  "port_name",
  "line_buf",
  "io_queue",
  "bits_buf",
  "db_named_table_entry",
  "ddll_processes",
  "ddll_handle",
  "port_data_lock",
  "nodes_monitor",
  "re_heap",
  "fd_entry_buf",
  "port_report_exit",
  "atom_text",
  "bif_timer_table",
  "atom_tab",
  "export_tab",
  "module_tab",
  "proc_tab",
  "port_tab",
  "timer_wheel",
  "code",
  "async_queue",
  "db_tabs",
  "db_match_pseudo_proc",
  "instr_info",
  "scheduler_data",
  "ddll_errcodes",
  "pre_alloc_data",
  "drv_tab",
  "driver_event_state",
  "pollset",
  "poll_fds",
  "poll_result_events",
  "fd_status",
  "fd_tab",
  "cs_prog_path",
  "heap",
  "old_heap",
  "heap_frag",
  "db_segment",
  "db_segment_tab",
  "db_stack",
  "db_trans_tab",
  "db_select_list",
  "db_dmc_error",
  "db_dmc_error_info",
  "db_term",
  "proc",
  "atom_entry",
  "export_entry",
  "module_entry",
  "reg_proc",
  "monitor_sh",
  "nlink_sh",
  "proc_list",
  "fun_entry",
  "db_tab",
  "driver_event_data_state",
  "driver_select_data_state",
  "drv_binary",
  "binary",
  "drv_internal",
  "driver_thread_opts",
  "driver_tid",
  "driver_mutex",
  "driver_cond",
  "driver_rwlock",
  "driver_tsd",
  NULL
};

const char *erts_alc_c2cd[] = {
  "invalid_class",
  "process_data",
  "code_data",
  "system_data",
  "atom_data",
  "ets_data",
  "binary_data",
  NULL
};

const char *erts_alc_a2ad[] = {
  "invalid_allocator",
  "sys_alloc",
  "temp_alloc",
  "sl_alloc",
  "std_alloc",
  "ll_alloc",
  "eheap_alloc",
  "ets_alloc",
  "fix_alloc",
  "binary_alloc",
  "driver_alloc",
  NULL
};

#endif /* #ifdef ERTS_ALC_INTERNAL__ */


/* ------------------------------------------------------------------------- */
#endif /* #ifndef ERL_ALLOC_TYPES_H__ */
